### ISSUE TITLE
Cocosim install Problem

### ISSUE THREAD

**Issue by SoftPro** [NASA-SW-VnV/CoCoSim#10]
Hello，
At present, I still haven't solved the problem of importing requirements. I said before that it seems to re execute the dependency according to "scripts / install_cocosim_lib. M". Do I execute it according to the following or other methods?
![image](https://user-images.githubusercontent.com/89380949/145807439-621dbb9e-f493-4ad5-9067-5c385c7331ec.png)
However, there will be other problems in this implementation, as shown in the figure：
There is another problem. When I execute the pre-built module of lustrec in "linux/bin", there will be a problem of missing library files. Is this the key to solving the problem?
Executing start_cocosim in matlab prompts that YICES2 cannot be found, is it related to the import requirements?
![image](https://user-images.githubusercontent.com/89380949/145808695-21195606-dbda-4bf1-9a33-aeee039d314e.png)

**Comment by SoftPro** [comment]
Hello，
Two pictures were not uploaded successfully just now, so I will show them again here.
![image](https://user-images.githubusercontent.com/89380949/145808919-27dbec94-0b5d-411e-afcf-a8297da4ba10.png)
![image](https://user-images.githubusercontent.com/89380949/145809196-c3fce801-a69c-4752-bb6e-92f3932c1f5d.png)

**Comment by SoftPro** [comment]
Hello,@andreaskatis

**Comment by andreaskatis** [comment]
Hi @SoftPro,

The message regarding YICES is not an issue. Last time I was able to check, the install_tools script does not properly work to fetch and build dependencies, on Linux machines. This is the main reason why the release already contains pre-built binaries for kind2, z3 and lustrec. In fact, install_cocosim calls the install_tools script with the prefix being the 'tools/verifiers/linux' folder. The install_tools script then checks if the binaries already exist (which they do), and skips the step in your screen shots that tries to fetch and build z3 and lustrec.

I still believe that your issue is because the install_cocosim_lib script fails at fetching and/or copying files from the cocosim2 repository into the CoCoSim directory. Did you try to manually perform the steps in the install_cocosim_lib file? This mostly means that you have to clone cocosim2 and move several files into CoCoSim.

I am specifically referring to the li es following the one below. Still, please make sure to perform any actions that precede this line, so that we can then pinpoint any further issues.

https://github.com/NASA-SW-VnV/CoCoSim/blob/5327a9761e9d24b240947d94c1e911a1d485c58d/scripts/install_cocosim_lib.m#L174

**Comment by andreaskatis** [comment]
Hello @SoftPro,

I think I just found out what the issue is. The option to import requirements is currently disabled in the last two releases:

https://github.com/NASA-SW-VnV/CoCoSim/blob/5327a9761e9d24b240947d94c1e911a1d485c58d/src/%2Bcocosim_menu/tools_menu.m#L73

The line above is commented out in the release source, but as you can see it is actually enabled on the repository code.

Still, running 'start_cocosim' should normally fix this by pulling updates from the repository. In your case this doesn't happen, for some reason. The good news is that you can force an update, though! Here's what you need to do:

1. Open MATLAB, navigate to the CoCoSim home folder
2. In the MATLAB terminal, run 'cocosim_force = 1;'. This will set the corresponding flag to force pull from the repository.
3. Run 'start_cocosim'. You should now see the script trying to update the source code by pulling from github.

Let me know how this goes!

**Comment by SoftPro** [comment]
Hello，@andreaskatis
I execute 'cocosim' according to your method_ force = 1;'， But it doesn't seem to work. You can see the following figure:
![image](https://user-images.githubusercontent.com/89380949/145921679-edf3a996-f4db-4158-a40e-5f7e0b3d4f15.png)

**Comment by SoftPro** [comment]
Hello，@andreaskatis
Thank you very much for your answer. I have solved the problem.
I copied the file of cocosim2 into cocosim, and then executed start in MATLAB_ Cocosim has solved this problem. Is it unnecessary to execute install under cocosim / scripts_ Cocosim, because some errors will appear when I execute it.

**Comment by andreaskatis** [comment]
Hi @SoftPro,

I'm glad you were able to figure this out. To answer your question, running 'install_cocosim' is necessary. It would be nice to know what errors you are referring to specifically, to determine if they are crucial or not. I believe that, under normal conditions, you shouldn't be getting any errors.

**Comment by SoftPro** [comment]
Hello,@andreaskatis
There are mainly the following problems. Z3 succeeded in making the first time. I don't think it's a problem to report an error in this place
![image](https://user-images.githubusercontent.com/89380949/145964344-20fd42a6-99de-4c60-b09f-bfd0f91ddd55.png)
![image](https://user-images.githubusercontent.com/89380949/145964645-b41fd627-c33b-4e5b-a097-a722a3b25d8a.png)
![image](https://user-images.githubusercontent.com/89380949/145964772-b6220c7e-718f-4932-b707-8a27d50fac19.png)
![image](https://user-images.githubusercontent.com/89380949/145964857-55f1aaac-248e-41e3-bd91-fc9af61905f5.png)
[bootstrap.log](https://github.com/NASA-SW-VnV/CoCoSim/files/7710101/bootstrap.log)
Above is my bootstrap Log file. I'm not sure whether these problems will cause problems with the use of cocosim.

**Comment by andreaskatis** [comment]
Hi @SoftPro,

Thank you for the response. None of these errors should give you further issues while using CoCoSim. They are all related to the step of fetching and building z3/LustreC/Kind 2, which is currently not properly working for Linux. The next release of the tool should have these issues resolved. 

If you are curious to know more though, you can see some more information in the bootstrap.log. 

The first error relates to the version for 'opam',which is currently required to be some version between 2.0.0 and 2.1.0.

The second error pops up at the step of fetching and building kind2. It appears that the latest version of kind2 requires ocaml >= 4.09, while 4.07.0 is detected on your machine.

**Comment by SoftPro** [comment]
Hello,@andreaskatis
OK, thank you very much for your answer.

**Comment by SoftPro** [comment]
Hello,@andreaskatis
There is no lustrec file under linux / bin of my cocosim, and then the import of requirements will fail. Is it because I execute/ install_ Cocosim, the reason for the problem in lustrec installation and how to solve it.
![image](https://user-images.githubusercontent.com/89380949/146189172-78452ca0-dca0-4b06-b48c-010c04a625f4.png)
![image](https://user-images.githubusercontent.com/89380949/146188469-48bf209d-fa05-4a30-ad6d-c971caac5614.png)

**Comment by andreaskatis** [comment]
Hi @SoftPro

The 'install_tools' script is supposed to put the lustrec binary in the bin folder for you, but apparently it hasn't.

You can see what happens exactly if you read the lines, starting from the link below:

https://github.com/NASA-SW-VnV/CoCoSim/blob/5327a9761e9d24b240947d94c1e911a1d485c58d/scripts/install_tools#L731

In this case, a quick fix would be to just manually move the lustrec binary under 'tools/verifiers/linux' into 'tools/verifiers/linux/bin' yourself.

Please make sure that the binary also has the correct permissions to run:

'chmod +x CoCosim/tools/verifiers/linux/bin/lustrec'

**Comment by SoftPro** [comment]
Hello,@andreaskatis
There is no lustrec file in my 'tools / verifiers / Linux' directory, and there is this file in my 'tools / verifiers / Linux / bin' of cocosim2, but there will be a lack of 'libgmp so. 3 ' this library. Is there any other way to deal with it？

**Comment by andreaskatis** [comment]
The downloaded release contains a lustrec binary under tools/verifiers/linux/bin.

If it's not there, please re-download the release and move the binary to the same destination under your existing installation.

If you are still getting the libgmp error, this is probably because your Linux installation is missing the corresponding library, and you would need to manually install it (I would just search online on how to do this for your specific OS).

**Comment by SoftPro** [comment]
Hello,@andreaskatis
I just solved the libgmp problem, but arrow H seems to be the library in cocosim. Where should I find this.
![image](https://user-images.githubusercontent.com/89380949/146200613-0ab66179-7c57-460b-8ee2-3f3201816f92.png)

**Comment by SoftPro** [comment]
Hello,@andreaskatis
The reason seems to be the problem of index path. How to modify it？

**Comment by SoftPro** [comment]
Hello,@andreaskatis
I created the index directory, and then put arrow C and other files are copied under it and the problem is solved successfully. However, I want to know how to modify the index directory. If it is too troublesome, I won't solve the problem.
![image](https://user-images.githubusercontent.com/89380949/146210793-e7cf6f89-c1fc-4a2d-813a-9a4b32240a0b.png)

**Comment by andreaskatis** [comment]
HI @SoftPro,

I am currently away on vacation and don't have access to the code. Is this a happening when using the pre-built binary for lustrec, that came with the release? If yes, you can try two things:

1. Try replacing the binary with the one from release v1.1
2. If (1) does not work, then you can try manually installing lustrec from source, following lines 733-771 in scripts/install_tools ( https://github.com/NASA-SW-VnV/CoCoSim/blob/5327a9761e9d24b240947d94c1e911a1d485c58d/scripts/install_tools#L733)

**Comment by SoftPro** [comment]
Hello,@andreaskatis
I'm sorry to disturb your rest time, but I'm in a hurry recently. Excuse me, what is the reason for the kind2 execution error in the verification process, and then how to solve it.
![image](https://user-images.githubusercontent.com/89380949/146396131-dd7704ff-4632-4212-978b-076e09f05bf6.png)
I put kind2 and Z3 in cocosim2 under the directory, but it still shows that there are no SMT tools in the verification process. This is the same as my execution in the 'scripts' directory/ install_ Does it matter that cocosim skips Z3, lustrec and kind2 installation
![image](https://user-images.githubusercontent.com/89380949/146402117-9910c89f-5530-4248-a004-80c8b80a34db.png)
Here are the mistakes you saw before：
![image](https://user-images.githubusercontent.com/89380949/146402721-4d086e99-7ef7-4d87-a6d5-1bb8894aa76b.png)

**Comment by andreaskatis** [comment]
Not sure what the exact issue is, as there are many possibilities. The most straightforward way to deal with this is to build both z3 and kind2 from source.

I suggest that you try and use kind 2 v1.1 and z3 v4.8.8, as I am not currently sure if later versions are compatible.

Kind 2 : https://github.com/kind2-mc/kind2/releases/tag/v1.1.0

Z3 : https://github.com/Z3Prover/z3/releases/tag/z3-4.8.8

**Comment by SoftPro** [comment]
Hello,@andreaskatis
Thank you very much. I have solved this problem, but when I ran your example, there was a verification error. I think there should be no problem with the example provided by this tool. You can take a look at the following problems. I don't know if it is my operation problem.
![image](https://user-images.githubusercontent.com/89380949/146474388-d2af06d7-269e-49fc-bc1b-b07fc1fdc98d.png)
![image](https://user-images.githubusercontent.com/89380949/146474462-32ee64cb-faf7-4755-b7a2-3a9a4f18fda0.png)

**Comment by andreaskatis** [comment]
The default guarantees in the example are invalid,and the result in your screen shot is claiming the same. You can click on each guarantee in this report to observe a counterexample that indicates at least one case where the guarantee is violated.

Given the results of this report it then only remains to look at the implementation and make sure that it does properly compute the absolute value, in any case. As I mentioned, this is not the case for the unchanged simulink model. The counterexamples will give you a version good idea as to why this is true. I'll leave out any further details for now, to give you the opportunity to figure it out on your own!

If you are still struggling, feel free to attach the counterexample reports here, so that we can continue to discuss the example.
