### ISSUE TITLE
distutils not found while installing cocosim on virtual machine

### ISSUE THREAD

**Issue by MKapuria** [NASA-SW-VnV/CoCoSim#15]
Hi,

I'm trying to install cocosim on a virtual machine running ubuntu 22.04. I downloaded the .zip file from here: https://github.com/NASA-SW-VnV/CoCoSim/releases/tag/v1.1

After extracting the files i run 'install_cocosim' from the command line and i receive this error:
```
vboxuser@Ubuntu:~/MATLAB/CoCoSim/scripts$ ./install_cocosim
==> Checking required dependencies
==> Found all required utilities
==> Checking for CMake
==> Found CMake 3.22.1
==> Checking for m4
==> Found m4 1.4.18
==> Checking for Python
==> Found Python 3.10.12, version too old, skipped
==> Found Python 3.10.12, version too old, skipped
install_tools: error: Missing required python module: distutils
```
Can you please explain this error to me? Do i need to have python to run cocosim in MATLAB? 

If I run cocosim without completing this step, then none of the verifiers binaries get installed and im unable to do any verification.

**Comment by andreaskatis** [comment]
Hi @akaph2p,

Thanks for trying out CoCoSim! The installation script attempts to install everything that may be required by cocosim.

Python and its distutils package are required for the Zustre backend. If you want to skip this you can comment out the following line in 'scripts/install_tools' : 

 https://github.com/NASA-SW-VnV/CoCoSim/blob/5c1597ab725d9bf8a790e4194d5d54460a6584c9/scripts/install_tools#L498

And run the script again.

Best Regards,

Andreas

**Comment by MKapuria** [comment]
Thats strange, in my 'install_tools' scripts, 'exit 4' is actually on line 487. Did i download an outdated release?

**Comment by andreaskatis** [comment]
Hi @akaph2p,

If you downloaded the code from the Releases page, then yes you have an out of date version.

We stopped publishing releases this way because of compatibility issues with the included pre-built binaries.

Please clone the repository instead, to get the most recent version of the code.

Best Regards,

Andreas

**Comment by MKapuria** [comment]
Thank you, I cloned the repository and installed CoCoSim. 

However, I tried to verify the 'absolute' and 'bacteria population' examples that come with CoCoSim, but i received similar errors both times, where the verification is unknown:

```
(Result)[Property checking]  result for property node [absSpec_16_000[l133c2].guaranteeabs_lpar_output_rpar__equal_abs_lpar_inpu_19_000]: UNKNOWN
(Result)[Property checking]  result for property node [absSpec_16_000[l133c2].guaranteeoutpt_gt__equal_0_33_000]: UNKNOWN
```

Is there something I'm missing?

**Comment by andreaskatis** [comment]
Hi @akaph2p ,

Are you using an Ubuntu machine? If yes, are you running MATLAB using the additional library reference mentioned below?

> Make sure that your environment has libstdc installed. MATLAB needs to always be called with the following flag (replace "version" suffix in the LD_PRELOAD path with your installed version, tested on versions 6.0.28 and 6.0.29 so far):

>LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.version /path/to/matlab/binary

If yes, then please send me a copy of the MATLAB terminal output for one attempt (any example will do). Before running the verification task, run the following command in the MATLAB terminal

`cocosim_debug=1`

Best Regards,

Andreas

**Comment by MKapuria** [comment]
Hi,

After running MATLAB using LD_PRELOAD, the verification seems to be working now. Thank you. 

I ran the bacteria population example and most properties were proved true, but a few were still unknown. Is that by design? 

```
Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000._one_mode_active]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].stable_2083_000[l705c3]]: UNKNOWN
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].increasing_2042_000[l697c3]]: UNKNOWN
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].decreasing_52_000[l681c3]]: UNKNOWN
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].guaranteepopulation_gt_0_152_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].guarantee1_158_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].ensure2_123_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].ensure1_63_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].ensure3_137_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].guarantee3_170_000]: SAFE
(Result)[Property checking]  result for property node [bacteriaPopulationSpec_42_000[l721c2].guarantee4_1993_000]: SAFE
(Result)[run_kind2] Verification results are exported to Json file: /home/vboxuser/MATLAB/CoCoSim/examples/contract/cocosim_output/bacteriaPopulation_PP/bacteriaPopulation_PP_KIND2_verificationResults_07-Jan-2024-15:36:01.json


```

**Comment by andreaskatis** [comment]
Hi @akaph2p,

Apologies for the belated response. The "unknown" properties that you see in the terminal are actually modes that are defined as part of the contract. Kind 2 checks these modes w.r.t. reachability (so as to prove that their corresponding requirements are not vacuously satisfied, by the mode never being exercised). This reachability result is currently interpreted as an "unknown" result in CoCoSIm.

You can double check this by heading into the `cocosim_output` folder that was created in the same folder where your Simulink model is (I guess this is under `CoCoSim/examples/contract` in this case). You can then directly run Kind 2 on the generated Lustre program as follows:

`kind2 --modular true --compositional true bacteriaPopulation_PP.KIND2.lus`

You'll then see the corresponding properties identified as reachable. In essence, any indirect property that is defined as part of the contract, is not considered when displaying the final analysis results at the CoCoSim level. For such properties, their corresponding analysis results are mapped as "unknown".

This is only just a convention that is currently in place. If you believe that this information is useful for the kind of analysis that you perform, I can always revisit this part and adjust it so that the final report includes it.

Best Regards,

Andreas

**Comment by MKapuria** [comment]
Thank you for the explanation, Andreas. This convention should be okay for me.
